Deployment script cleanup
instante/skeleton pull request #16
Opened 2016-09-30 13:28 UTC by honzagula

2016-09-30 15:19 UTC, richard-ejem requested changes

2016-09-30 15:19 UTC, richard-ejem commented on bin/deployment/ProjectDeployer.php
> +            throw new InvalidStateException('Cannot initialize already configured project\n');
This won't work - \n sequence does not work in 'single quotes'

2016-10-03 13:44 UTC, honzagula commented on bin/deployment/ProjectDeployer.php
> +            throw new InvalidStateException('Cannot initialize already configured project\n');
Fixed

2016-10-18 09:33 UTC, richard-ejem approved these changes

2016-10-18 09:33 UTC, merged