Gulp task runner
instante/skeleton pull request #18
Opened 2016-10-18 08:59 UTC by honzaskovran

Grunt replaced by gulp with support of ES6. Added option to choose css preprocessor (sass/less)

2016-10-18 09:31 UTC, richard-ejem requested changes

2016-10-18 09:31 UTC, richard-ejem commented on bin/deployment/init-project.php
> -
Please return the empty lines back :)

2016-10-18 09:31 UTC, richard-ejem commented on bin/deployment/ProjectInitializer.php
> +        //unlink(__DIR__ . '/ProjectInitializer.php');
why? project initializer should remove itself after initialize.

2016-10-18 09:31 UTC, richard-ejem commented on frontend/package.json
> -    "name": "YourAppName",
Please return to 4-space indentation

2016-10-18 09:31 UTC, richard-ejem commented on bin/deployment/ProjectInitializer.php
> +                $this->removeDirecory($this->dir . '/frontend/src/less');
The actual work should be done in initialize() method. This setter should only prepare configuration in ProjectInitializer attributes.
Please add SASS/LESS choice to initializeFromConsole() method too.

2016-10-18 09:31 UTC, richard-ejem commented on bin/deployment/ProjectInitializer.php
> +                $this->removeDirecory($this->dir . '/frontend/src/sass');
dtto should happen in initialize()

2016-10-18 09:31 UTC, richard-ejem commented on bin/deployment/ProjectInitializer.php
> +        $this->configureGulpfile($preprocessor);
dtto should happen in initialize()

2016-10-18 12:31 UTC, honzaskovran commented
Done, please recheck

2016-10-20 09:11 UTC, honzaskovran commented
Travis is now passing. I also added test for gulpfile configuration

2016-10-20 10:07 UTC, richard-ejem approved these changes

2016-10-20 12:11 UTC, merged